### ISSUE TITLE
Gnome keyring and Kwallet are not getting unlocked 

### ISSUE THREAD

**Issue by tim-gromeyer** [sbradnick/hyper-v-enhanced-session#2]

**Comment by sbradnick** [comment]
What would that have to do w/ 'hyper-v-enhanced-session'?

**Comment by tim-gromeyer** [comment]
Normally when starting the enhanced session and logging it with xrdp, it should unlock the keyring. Since this should be archivable by adding a couple of files, and this repo provides files for the enhanced session, I opened an issue here

**Comment by sbradnick** [comment]
> Normally when starting the enhanced session and logging it with xrdp, it should unlock the keyring.

I'm not sure I agree with that. I'm not saying you're wrong, but I don't think the expectation lies w/ xrdp (unless it specifically accounts for it?) or 'hyper-v-enhanced-session' (I suppose some other iteration, in Ubuntu perhaps, might do it) but rather with the user/DE/WM. I'd assume Gnome and KDE have some mechanism (maybe tied to PAM?) to unlock it at login, hence why I feel it moreso lies with them than a package like this. _Maybe_ when I was using vanilla Gnome (and not so much the keyring - I was anti-keyring for a while) it would unlock an empty one and/or auto create some type of "Login" keyring but I found it very frustrating, if not useless and I put time into disabling it completely - which I'm not sure I was even successful. I've never really been a KDE user, so I don't know much about what goes on there. I spend 99.9% of my time in i3 (previously bspwm, before that awesomewm) so I'm less familiar with how more mainstream WM/DE's do it.

I use i3 daily, icewm on occasion and I don't want or expect either to unlock my keyring automatically; I have a script which does it and I run it manually after I log in (don't see the point in adding it to my i3 startup). It makes use of a Yubikey and `pass`, but it's still pretty simple, basically boiling down to: `echo -n <password grabbed from pass> | /usr/bin/gnome-keyring-daemon --unlock -r -d --components=secrets` - I don't feel like there's a 1-size-fits-all answer for keyrings and I don't think 'hyper-v-enhanced-session' needs some crazy case statement to try and handle different ways. If a user is making a choice to use Gnome,KDE,XFCE,etc. I think they can also put something together to unlock the keyring if their DE/WM doesn't take care of it.

> Since this should be archivable by adding a couple of files, ...

If you want to be less vague about that, I'd certainly dig into it - but at this point I have very little interest in going down a rabbit hole I don't really agree with.
